### ISSUE TITLE
Linking CXX shared library /root/build_xc/xc/lib/libXcBib.so failed

### ISSUE THREAD

**Issue by GJoe2** [xcfem/xc#107]
**Describe the bug**
After following the solution in #106, I upgraded g++-10 , gcc-10 and gfortran-10, then when it gets 99% 
`[ 99%] Linking CXX shared library /root/build_xc/xc/lib/libXcBib.so`
It failed with :
```
/usr/bin/ld: CMakeFiles/XcBib.dir/solution/system_of_eqn/eigenSOE/BandArpackSOE.cpp.o: in function `XC::BandArpackSOE::save() const':
BandArpackSOE.cpp:(.text+0xa55): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/XcBib.dir/build.make:19369: /root/build_xc/xc/lib/libXcBib.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:202: CMakeFiles/XcBib.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
[log.txt](https://github.com/xcfem/xc/files/8239840/log.txt)

What I did wrong? I have no idea
[CMakeOutput.log](https://github.com/xcfem/xc/files/8239892/CMakeOutput.log)
[CMakeError.log](https://github.com/xcfem/xc/files/8239893/CMakeError.log)

**Comment by lcpt** [comment]
Any news about this?

**Comment by lcpt** [comment]
I imagine this is no longer an issue.
