### ISSUE TITLE
Can not create folder with "aux" name in windows

### ISSUE THREAD

**Issue by ebrahimraeyat** [xcfem/xc#117]
Hello @lcpt .
I wanted to pull repo in windows 10, but windows can not create directory with name "aux":

[folder](https://github.com/xcfem/xc/tree/master/python_modules/materials/sections/structural_shapes/aux)

related issue:

[Unable to create folder named](https://social.technet.microsoft.com/Forums/Azure/en-US/d1cf7394-a39b-46bf-823d-46f33b2f78d0/unable-to-create-folder-named-aux-anywhere-in-the-disk?forum=w7itprogeneral#:~:text=Answers&text=This%20is%20a%20part%20of,%2C%20LPT7%2C%20LPT8%2C%20LPT9.)

**Comment by lcpt** [comment]
You'll need to pull the repository in a Unix-like file system. For some reason, "aux" is a forbidden name in Microsoft file systems since the days of MS-DOS.

**Comment by lcpt** [comment]
I'll close that. It this becomes the last pitfall to compile the code under MS Windows, we can always reopen it.
