### ISSUE TITLE
lower and upper analysis.h & Analysis.h in same directory, error on windows os

### ISSUE THREAD

**Issue by ebrahimraeyat** [xcfem/xc#124]
windows OS does not accept the same filename with lower and upper case, for example analysis.h and Analysis.h in one directory.

it is on ```src\solution\analysis\analysis```

 - OS: Windows

**Comment by lcpt** [comment]
That's right, but the source code of XC is written for Unix systems. As you know, you can use it in Windows systems through WSL. I don't see the issue.
