### ISSUE TITLE
mumps dependencies

### ISSUE THREAD

**Issue by g-schaffer** [xcfem/xc#129]
link [MUMPS: MUltifrontal Massively Parallel sparse direct Solver](http://mumps.enseeiht.fr/) from https://github.com/xcfem/xc/blob/master/install/dependencies_list.md
is dead, can you provide another link?

**Comment by lcpt** [comment]
Thanks for the catch, I've fixed the broken link in commit #a941002
Anyway, the correct URL is: https://mumps-solver.org
