### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by happygug85** [xcfem/xc#132]
I have a laptop with linux mint 21.3. 
When I run ~/build_xc/build-xc$: sudo cmake ../xc/src
I have a error:
CMake version is not greater than 3.20.0
-- xc project dir: /home/happy/build_xc/xc/
-- xc include dir: /home/happy/build_xc/xc/src/
-- xc lib dir: /home/happy/build_xc/xc/lib
-- ************* find packages begins ****************
-- The imported target "vtkParseOGLExt" references the file
   "/usr/bin/vtkParseOGLExt-7.1"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-7.1/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-7.1/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtk" references the file
   "/usr/bin/vtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-7.1/VTKTargets.cmake"
but not all the files it references.

-- The imported target "pvtk" references the file
   "/usr/bin/pvtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-7.1/VTKTargets.cmake"
but not all the files it references.

CMake Warning at /usr/lib/x86_64-linux-gnu/cmake/CGAL/CGALConfig.cmake:92 (message):
  CGAL_DATA_DIR cannot be deduced, set the variable CGAL_DATA_DIR to set the
  default value of CGAL::data_file_path()
Call Stack (most recent call first):
  /home/happy/build_xc/xc/CMake/find_packages.cmake:29 (find_package)
  CMakeLists.txt:79 (INCLUDE)

-- Using header-only CGAL
-- Found GMP: /usr/lib/x86_64-linux-gnu/libgmp.so
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.48")  
-- Boost include dirs: /usr/include
-- Boost libraries:    
-- Using gcc version 4 or later. Adding -frounding-math
-- GNUGTS include dir: /usr/include
-- GNUGTS libraries: /usr/lib/x86_64-linux-gnu/libgts.so
-- Found CImg: 
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.62")  
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0") found components: python 
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0") found components: system regex filesystem thread math_c99 math_c99f math_c99l math_tr1 math_tr1f math_tr1l 
-- PYTHON_LIBRARIES = /usr/lib/x86_64-linux-gnu/libpython3.10.so
-- PYTHON_EXECUTABLE = /usr/bin/python
-- PYTHON_INCLUDE_DIRS = /usr/include/python3.10
-- Looking for execinfo
-- Looking for execinfo headers - found
-- Found plotter.h: /usr/include
-- Found plotter lib: /usr/lib/x86_64-linux-gnu/libplotter.so
-- Found GMP: /usr/lib/x86_64-linux-gnu/libgmp.so
-- SQLite3 library found.
-- Found Arpack: /usr/lib/x86_64-linux-gnu/libarpack.so
-- Found Arpack++: /usr/include/arpack++
-- Found Arpack++ lib: /usr/lib/x86_64-linux-gnu/libarpack++.so
-- Found Umfpack: /usr/lib/x86_64-linux-gnu/libumfpack.so
-- Found DMUMPS: /usr/lib/x86_64-linux-gnu/libdmumps.so
-- Found PETSC include dir: /usr/include/petsc
-- Found PETSCCONF include dir: /usr/include/petsc
-- Found PETSC library: /usr/lib/x86_64-linux-gnu/libpetsc.so
-- Found SuperLU: /usr/include/superlu
-- Spectra not found (DavidsonSymEigsSolver.h)
-- Berkeley DB 5.3.28: (September  9, 2013)
-- Found METIS: /usr/include
-- found sqlplus version: /bin/sh: 1: /bin/sqlplus: not found
-- Guessed ORACLE_OCI_VERSION value: 10G_R2
-- Oracle not found.
-- Oracle: You can specify includes: -DORACLE_PATH_INCLUDES=/usr/include/oracle/10.2.0.3/client
--    currently found includes: ORACLE_INCLUDES-NOTFOUND
-- Oracle: You can specify libs: -DORACLE_PATH_LIB=/usr/lib/oracle/10.2.0.3/client/lib
--    currently found libs: ORACLE_LIBRARY_OCCI-NOTFOUND;ORACLE_LIBRARY_CLNTSH-NOTFOUND;ORACLE_LIBRARY_LNNZ-NOTFOUND
-- GMSH_ROOT_DIR not set (and that's probably OK).
-- Gmsh headers: GMSH_INCLUDE_DIRS-NOTFOUND
-- Gmsh libraries: GMSH_LIBRARIES-NOTFOUND
CMake Error at /home/happy/build_xc/xc/CMake/FindGMSH.cmake:122 (MESSAGE):
  Could not find GMSH
Call Stack (most recent call first):
  /home/happy/build_xc/xc/CMake/find_packages.cmake:82 (find_package)
  CMakeLists.txt:79 (INCLUDE)

-- Configuring incomplete, errors occurred!
See also "/home/happy/build_xc/build-xc/CMakeFiles/CMakeOutput.log".
See also "/home/happy/build_xc/build-xc/CMakeFiles/CMakeError.log".

How I can resolve?

**Comment by lcpt** [comment]
You need to install the [GMSH]( https://community.linuxmint.com/software/view/gmsh) libraries. I don't know which version of Gmsh comes with Linux Mint, but it is probably OK (Gmsh 4.8 or later will do).

**Comment by happygug85** [comment]
Solved!
I used the shell for install gsmh's dependence

**Comment by lcpt** [comment]
OK, good. I'll close this issue then.
