### ISSUE TITLE
Incorporate SIA punching shear verification routines 

### ISSUE THREAD

**Issue by lcpt** [xcfem/xc#16]
Integrate the verification routines that are at:

[punchingShearSIA.zip](https://github.com/lcpt/xc/files/118002/punchingShearSIA.zip)

add some verification tests:
[Ancoplus.pdf](https://github.com/lcpt/xc/files/118007/Ancoplus.pdf)
[dimensionnement ancoplus.pdf](https://github.com/lcpt/xc/files/118008/dimensionnement.ancoplus.pdf)

**Comment by ebrahimraeyat** [comment]
I know that it is related to SIA code, but I have been written a punch Workbench in FreeCAD that can automatically read the [CSI SAFE](https://www.csiamerica.com/products/safe) exporting file and calculate shear punching:

[punch Workbench](https://github.com/ebrahimraeyat/Civil)

**Comment by lcpt** [comment]
Too old.
