### ISSUE TITLE
 Wind and snow load generation

### ISSUE THREAD

**Issue by lcpt** [xcfem/xc#20]
Write utilities that make easier (not automatic) to generate wind ans snow loads.

**Comment by lcpt** [comment]
Ana wrote some routines to compute wind action on cylindrical surfaces [here](https://github.com/xcfem/xc/blob/master/python_modules/actions/wind/base_wind.py).

**Comment by ebrahimraeyat** [comment]
Hi @lcpt. What about snow load? Is there any routine? Thanks.

**Comment by lcpt** [comment]
Hi @ebrahimraeyat

Not much. There are some routines [here](https://github.com/xcfem/xc/blob/master/python_modules/actions/snow/SIA_snow.py) about snow loads according to Swiss standards.

**Comment by lcpt** [comment]
Some work has been done [here](https://github.com/xcfem/xc/tree/master/python_modules/actions/snow) and [here](https://github.com/xcfem/xc/tree/master/python_modules/actions/wind).

**Comment by ebrahimraeyat** [comment]
Thanks. As a python comment:

I think it is better to use dictionary instead of if else:

```python
retval= 1.2 # pesimistic asumption
if(riskCategory==1):
    retval= 0.8
elif(riskCategory==2):
    retval= 1.0
elif(riskCategory==3):
    retval= 1.1
elif(riskCategory==4):
    retval= 1.2
else:
    lmsg.error('risk category: '+str(riskCategory)+' unknown.')
return retval
```

convert to:

```python
riskcategory_importance_factors = {
    1: 0.8,
    2: 1.0,
    3: 1.1,
    4: 1.2,
}
importance_factor =riskcategory_importance_factors.get(riskCategory, None)
if importance_factor is None:
    lmsg.error('risk category: '+str(riskCategory)+' unknown.')
    importance_factor = 1.2
return importance_factor
```python
