### ISSUE TITLE
Overload getNumEdges for elements that have nodes inside edges (like QuadBase9N).

### ISSUE THREAD

**Issue by lcpt** [xcfem/xc#24]
Make that for all classes that define this kind of elements (20nbrick, 27nbrick,...).

**Comment by ebrahimraeyat** [comment]
Hi @lcpt, if I understand you, with FreeCAD API we can get nodal force correctly for all elements:

[get node loads](https://forum.freecadweb.org/viewtopic.php?p=379021#p379021)

**Comment by lcpt** [comment]
Uf! This is an old issue. The question here was to avoid that middle edge nodes behave like corner nodes with respect to edge counting, thats all.  I forgot to close the issue.
