### ISSUE TITLE
Export data out of XC

### ISSUE THREAD

**Issue by berndhahnebach** [xcfem/xc#33]
Is one of the following possible and if yes how? workingModel of ana is agreat example to play with ...

- export geometry entries to step, dxf, txt or any other format?
- export fem-mesh to vtk, unv, stl or any other format?
- export results to vtk?

Cheers bernd

**Comment by lcpt** [comment]
There exist a package that exports the the geometry to SCIA XML: [sciaXML](https://github.com/lcpt/xc/tree/master/python_modules/import_export/sciaXML). It can export also the mesh but the SCIA model that results is not very useful. You can see an example here: [xc_to_scia.py](https://github.com/anaiortega/XCmodels/blob/master/underpassCrissier/xc_to_scia.py).

There is also the module [DxfReader.py](https://github.com/lcpt/xc/blob/master/python_modules/import_export/DxfReader.py) that can be use to import the geometry from a DXF file. You can see an example here: [import_from_dxf.py](https://github.com/anaiortega/XCmodels/blob/master/tour_peilz/import_from_dxf.py).

**Comment by lcpt** [comment]
There is also some methods in the module [NeutralMeshDescription.py](https://github.com/lcpt/xc/blob/master/python_modules/import_export/NeutralMeshDescription.py) that allos to import a mesh from DAT files generated by Salome. You can see an example here: [dat_to_xc.py](https://github.com/anaiortega/XCmodels/blob/master/salome_to_xc/to_xc/dat_to_xc.py).

**Comment by lcpt** [comment]
You can also export the mesh to Paraview file format using vtkXMLUnstructuredGridWriter in VTK; I've added an example here: [mesh_to_vtk_file_test.py](https://github.com/anaiortega/XCmodels/blob/master/tour_peilz/mesh_to_vtk_file_test.py). The model imported in Paraview (with some warnings in the process) looks like that:
![paraview_screenshot](https://user-images.githubusercontent.com/12873038/46628751-f003ec80-cb3e-11e8-8906-5574516af23f.png)

**Comment by lcpt** [comment]
I Imagine there is a way to export the results to VTK (Paraview) too but i've never used it.

Cheers.
Luis

**Comment by berndhahnebach** [comment]
wow, cool that's the stuff I was looking for ... There is a lot to learn and try out ...
