### ISSUE TITLE
Tons of documentation questions

### ISSUE THREAD

**Issue by berndhahnebach** [xcfem/xc#34]
issues are not the best way to ask all the question I have ATM, but we do not have any better ATM, do we? There is neither a forum or a mailing list?

Bernd

**Comment by lcpt** [comment]
Well, we have two gitter rooms:

[https://gitter.im/xc_development/Lobby](url)
[https://gitter.im/xc_development/xc_documentation](url)

Maybe that can do the trick for the moment.

**Comment by berndhahnebach** [comment]
I will have a look. I've never worked with github.

BTW: the links are wrong ...

https://gitter.im/xc_development/Lobby
https://gitter.im/xc_development/xc_documentation

**Comment by lcpt** [comment]
Ups ! Sorry. Now I realiza my error...

**Comment by berndhahnebach** [comment]
I did one too. I've been working with github for years, but I've never worked with gitter!
