### ISSUE TITLE
Set up an github organization xcfem

### ISSUE THREAD

**Issue by berndhahnebach** [xcfem/xc#42]
Hi ana, hi luis,
I quit often have a look at the issues and other stuff even when I'm on the way and it is quit cumbersome to keep the names of ana and your github. Furthermore for new user it is cumbersome to have different github to get xc repos. Furthermore on your github are repos not related to xc.

How about making an github organization xcfem and move all xc repos there. This will be the base and all other are forks including your own ones. Furthermore your own delopment or test or play branches will be in your github and not in the main repos. It is eay

**Comment by berndhahnebach** [comment]
it is easy to add or remove people to and from an organization. May be check FreeCAD github as example. As early in a project history as better to set up such common stuff.

cheers bernd

**Comment by lcpt** [comment]
Done. I've put some basic data. We can discuss it later.

See you in xcfem.

Cheers Luis.

**Comment by lcpt** [comment]
I imagine I can close this issue...

**Comment by berndhahnebach** [comment]
are you gone set it up? I would make it too, but since XC is your baby it would makes most sence to me if you gone set the github organiztion up.

bernd

**Comment by berndhahnebach** [comment]
see you in xcfem :-)

**Comment by lcpt** [comment]
It's my baby and Ana's and your's and anyone's else who wants to use it. As Eric Clapton says: "music is music, if you can play it it's yours".

Cheers Luis.

**Comment by berndhahnebach** [comment]
Ahh, you moved your repos, thus all forks and issues keeps alive. Thats cool! Just updated all links I have and I have access too and I know of to the organization.

**Comment by lcpt** [comment]
Normally Ana and you have access to all the stuff.

**Comment by berndhahnebach** [comment]
it has just started and I love it already, just type in github.com/xcfem and I'll be there ...
