### ISSUE TITLE
xc and opensees

### ISSUE THREAD

**Issue by berndhahnebach** [xcfem/xc#46]
Ĥi Luis
Hi Ana,

just some basic question. Is XC a fork of opensees or is it based on opensees and the opensees code in XC will be updated from time to time when opensees will be released in a new version?

cheers bernd

**Comment by lcpt** [comment]
There are also features, like linear buckling analysis or modal analysis, that  are not available in Opensees (as far as I know).

**Comment by berndhahnebach** [comment]
2004, wow what a long history XC has ...

Have you ever pushed back some of the changes to Opensees upstream?

**Comment by lcpt** [comment]
Hi.

No. As far as I know Openers is developed by a mostly academic community. I imagine that it is not impossible to become a member, but it seems not very easy....

I didn't found neither an easy way to make contributions to the source code.

Cheers Luis.

**Comment by berndhahnebach** [comment]
On FreeCAD we are very happy about any value contribution. But FreeCAD is a real community project. Might be opensees is different, but you never know ... it also depends how difficault it is to make a PR. On FreeCAD and XC it is very very easy.

anyway thanks for the informations Luis.

cheers bernd

**Comment by berndhahnebach** [comment]
related: https://forum.freecadweb.org/viewtopic.php?f=18&t=17061&p=268634#p268634

**Comment by berndhahnebach** [comment]
Wow, I did not know they are on Github too!

**Comment by lcpt** [comment]
Neither did I.

**Comment by lcpt** [comment]
It seems it's somebody which has uploaded the Opensees sources, not the Berkeley University itself.

**Comment by mhscott** [comment]
The OpenSees github repo is managed by Frank McKenna @fmckenna from UC Berkeley.  It is "official".

**Comment by ebrahimraeyat** [comment]
Hello @lcpt, I started to bring [opensees into freecad](https://github.com/ebrahimraeyat/FreeCAD/tree/opensees) as a solver, some question:
- how do you display rotation of nodes, with vtk? as i know, vtk only display translational DOF.
- what about for Moment, shear and Axial force for beam-column?
- i want to merge your some of your project into my project, do you think it is possible?

**Comment by lcpt** [comment]
Hi @ebrahimraeyat.
For the first two questions you can take a look to the examples that @berndhahnebach wrote (those that start with calculix_cantilever...) [here](https://github.com/xcfem/xc_examples).

The implementation of the Python interface of XC and OpenSees are quite different, apart from that don't see any major problems.

**Comment by ebrahimraeyat** [comment]
Thanks @lcpt . I will take a look to them.

**Comment by ebrahimraeyat** [comment]
thanks, i looked to those examples, my questions:
- do you produce opensees .tcl file or files for analysis internally? if yes, how can i obtain this file?
- do you use recorder of opensees for results? then you use vtk for show the results?

thanks

**Comment by lcpt** [comment]
Hi.

No I don't generate tcl files. All the communication between Python and C++ is done through the boos.python interface (see python_interface.tcc files in source code).

I retrieve the results asking directly the nodes, elements, ...

**Comment by ebrahimraeyat** [comment]
thank you for your quick answer. 
isn't opensees main solver of xc?! or you mean you directly use opensees c++ code for analysing with python wrapping? if this is, it is amazing. it is very interesting. is a gui for xc is in progress?

**Comment by lcpt** [comment]
Of course, it's the main solver, but as you pointed we use directly the C++ code.

About the GUI our idea is to integrate XC into FreeCAD and/or Blender as a "plugin" but, for now, I have not much time for this.

**Comment by ebrahimraeyat** [comment]
thanks @lcpt , as i found, if i continue my opensees solver in FreeCAD, I can't use xcfem for desing, because for xc we must define model with your library to be able to obtain results or other informations. is this true?

**Comment by lcpt** [comment]
Yes, that's true.

**Comment by ebrahimraeyat** [comment]
very thanks for your quick reply. some question:
- is this way you use is faster than to creating *.tcl file?
- what is your idea about openseespy? is it useful for your work or it is not require?
- is xc cross platform? i mean it can be, i know ATM it is only for linux.

**Comment by lcpt** [comment]
Hi again.

I don't know if it is faster or not I've never written more than a dozen lines in TCL. We started to write the Python interface in 2013, at this time there was no openseespy at all, so no, we don't use openseespy at all. The main problem to compile XC in Windows or Mac OS is the library dependencies we make an intensive use of libraries already available on a standard Linux distribution (CGAL, VTK, superlu, suitesparse, ...); some of these libraries are also available in other operating systems but some others don't (you can take a look [here](https://github.com/xcfem/xc/blob/master/install/packages_install_ubuntu_bionic.sh).

**Comment by ebrahimraeyat** [comment]
thanks @lcpt, I will continue my OpenSees in FreeCAD development and follow your work. I think for design structure I will look to your code.
