### ISSUE TITLE
porting to python3

### ISSUE THREAD

**Issue by ebrahimraeyat** [xcfem/xc#48]
Is there any plan to work with python3?  for installation it's give me print error frequently, because my default python evnironment is python3. thanks.

**Comment by Ghostom998** [comment]
Try a virtual environment

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lcpt** [comment]
Yeah we will migrate to Python 3 (we will need to migrate to VTK 7 sooner or later) but not immediately.

**Comment by ebrahimraeyat** [comment]
> Yeah we will migrate to Python 3 (we will need to migrate to VTK 7 sooner or later) but not immediately.

very thanks to you.
