### ISSUE TITLE
compiling on manjaro linux

### ISSUE THREAD

**Issue by ebrahimraeyat** [xcfem/xc#49]
Hello. Very thanks to your very usefull software. I try to install xc on manjaro linux with .sh installation file, but for xc_basic it gives me this boos error:

-- Could NOT find Boost
Unable to find the Boost header files. Please set BOOST_ROOT to the root directory containing Boost or BOOST_INCLUDEDIR to the directory containing Boost's headers.

I work with python and i don't underestand what this mean? thanks

**Comment by lcpt** [comment]
Thanks to you Ebrahim
The installation script doesn't find the development files for [boost libraries](https://www.boost.org). The package that contains those files in Ubuntu is called libboostX.XX-dev (where X.XX is the version). If you can find the corresponding package in Manjaro the problem will be fixed.

**Comment by lcpt** [comment]
It can be the boost version too. I'll try to tell CMake that any recent version of boost libraries will do it.

**Comment by ebrahimraeyat** [comment]
thanks. from [this](https://github.com/xcfem/xc/blob/5fd337eb2286f2e2cbb50cb38c5e2ffcfff0a9d2/install/install.scipts.linux.md) guid i had think that script will  resolve needed dependency packages needed to compile XC as mentioned on page.. i will try it on ubuntu, because my pacman in manjaro linux is broken.  thanks alot.

**Comment by berndhahnebach** [comment]
>  from [this](https://github.com/xcfem/xc/blob/5fd337eb2286f2e2cbb50cb38c5e2ffcfff0a9d2/install/install.scipts.linux.md) guid i had think that script will resolve needed dependency packages needed to compile XC as mentioned on page

installing dependencys works on debian and ubuntu only. Just read the readme carfully. I may try on manjaro in a virtual environment to update a the scripts for manjaro.

**Comment by lcpt** [comment]
> > from [this](https://github.com/xcfem/xc/blob/5fd337eb2286f2e2cbb50cb38c5e2ffcfff0a9d2/install/install.scipts.linux.md) guid i had think that script will resolve needed dependency packages needed to compile XC as mentioned on page
> 
> installing dependencys works on debian and ubuntu only. Just read the readme carfully. I may try on manjaro in a virtual environment to update a the scripts for manjaro.

Hi Bernd, thank you.

By the way I've already merged xc_basic into xc_utils so no need to deal with xc_basic anymore. I thought to delete the xc_basic repository in a few days, if you see a problem with that please let me know.
