### ISSUE TITLE
convergence problem

### ISSUE THREAD

**Issue by anaiortega** [xcfem/xc#50]
Hi, 
I have a problem with a steel bar defined by two lines. when using the points for line generation at coordinates  [0, 2.5, 5] the calculation of internal forces works fine, but if you move slightly the middle point and use coordinates [0, 2.5006250000000003, 5], an error is displayed:

XC::BandSPDLinLapackSolver::solve; WARNING - the LAPACK routines returned 161
XC::Linear::resuelve; WARNING the XC::BandSPDLinSOE failed in solve()
XC::StaticAnalysis::solve_current_step; the Algorithm failed at step: 0 with domain at load factor 1

Any idea of what is happening?

**Comment by lcpt** [comment]
Hi.

Yeah, I think so. Check if you forgot to restrain a degree of freedom (torsion maybe?) that, for some geometric configurations, is accidentally restrained due to the "microscopic" error of the nodes positions that are computed with floating point arithmetic.

**Comment by anaiortega** [comment]
You are spot on. Thank you!
