### ISSUE TITLE
cmake/ petsc compile error

### ISSUE THREAD

**Issue by christy1111** [xcfem/xc#53]
Hello,

could anyone provide some assistance with the following error? it occurs when I try to compile xc, with 
'cmake ../xc/src'.

I understand there is an issue with cmake identifying petsc, and that the xcfem code includes the script FindPETSc.cmake. 

I have PETSc 3.7 installed, and I am using Ubuntu 16. The XC package was downloaded on 28/12/18.

CMake Error at /home/chris/build_xc/xc/CMake/FindPetsc.cmake:32 (MESSAGE):
  No se encontró petsc.h
Call Stack (most recent call first):
  /home/chris/build_xc/xc/CMake/find_packages.cmake:36 (find_package)
  CMakeLists.txt:62 (INCLUDE)

**Comment by lcpt** [comment]
Hi

Can you type: 'locate pets.h' and put the result here?

Regards Luis.

**Comment by lcpt** [comment]
Hi again.

In my system (Ubuntu 18) the 'locate petsc.h' returns:

/usr/lib/petscdir/3.7.7/x86_64-linux-gnu-real/include/petsc.h
/usr/lib/petscdir/3.7.7/x86_64-linux-gnu-real/include/petsc/finclude/petsc.h
/usr/lib/petscdir/3.7.7/x86_64-linux-gnu-real/include/petsc/finclude/petsc.h90
/usr/lib/petscdir/3.7.7/x86_64-linux-gnu-real/include/petsc/finclude/ftn-auto/petsc.h90 

And FindPETSc.cmake locates the file trough the symbolic link in /usr/include:

/usr/include/petsc: symbolic link to /etc/alternatives/petscinclude

Have you installed the package petsc-dev int addition to libpetsc3.7?

Regards Luis.
