### ISSUE TITLE
compile XC on Debian Buster

### ISSUE THREAD

**Issue by berndhahnebach** [xcfem/xc#54]
Hi Luis,

I tried to compile XC on Debian Buster, but xc_utils fails on cmake because of missing mysql dev packages. The problem is on Debian Buster is package libmysql++-dev not available. See https://packages.debian.org/search?searchon=names&keywords=libmysql%2B%2B-dev  Do you have an idea how to fix this?

Ahh just realized the following ... but open the ticket anyway to not forget about ... 
I may try to install the sid or stretch package. It is not smart, but it could work because all of them are 3.2.2+pristine-2

I will report back.

cheers bernd

BTW: XC compile script's still run flawless on Debian Stretch and Ubuntu Bionic Beaver :-)

**Comment by berndhahnebach** [comment]
works great with package from stretch ... 

https://github.com/berndhahnebach/xc/blob/buster/install/packages_install_debian_10_buster.sh#L91-L92

will updates sciptes on master xc ...

**Comment by lcpt** [comment]
MySQL++ is no longer needed (you can use Python directly to interact with MySQL) (sorry for the inconvenience Bernd). I'll check twice and then I'll remove the reference to this package.

**Comment by lcpt** [comment]
I've removed all the references to libmysql++-dev. Now we can compile on Debian Strecht without dowloading this package from the Ubuntu repositories.
