### ISSUE TITLE
does this software depend on metis or parmetis?

### ISSUE THREAD

**Issue by salmanishere** [xcfem/xc#57]
Hi, I would be thankful if you answer my question. It may be a little bit novice but anyway I ask it. 

Does this software depend on [metis](https://packages.debian.org/stable/libmetis-dev) (free software) or [parmetis](https://packages.debian.org/stable/libparmetis-dev) (non-free software)?

Because in the CMake directory, [this file](https://github.com/xcfem/xc/blob/master/CMake/FindMETIS.cmake) tries to find _metis_ while [this file](https://github.com/xcfem/xc/blob/master/install/packages_install_debian_stretch.sh) says that _metis_ and _parmetis_ both are the dependencies.

I asked this question because I couldn't find a file where _parmetis.h_ is included.

@berndhahnebach

**Comment by lcpt** [comment]
Hi.

You're right parmetis is not needed. Maybe it was needed when I tried to make XC read and write Salome's MED files directly. I'll double check that all goes OK without parmetis and remove those lines from the installation scripts. Thank you!

Regards. Luis.

**Comment by lcpt** [comment]
Done!

No need of parmetis.
