### ISSUE TITLE
Ill-conditioned problem?

### ISSUE THREAD

**Issue by anaiortega** [xcfem/xc#58]
Hi,
I'm trying to make a test on long-term prestress losses over a single section (see test_long_term_restress_loss.py in work-in-progress repository), but in the first stage (prestress transfer) it returns already a 2% error. It seems that the problem is ill-conditioned (the displacement in the element axis and rotation in its strong axis are free in one of its nodes). The message that pops up is:

XC::Node::checkReactionForce; the node: 2 has not constraints on DOF: 0 and, however, it has a reaction with value: 4385.68 on this degree of freedom, it seems that the solution method and/or tolerances are not well suited to the problem. (tol= 19.2473
XC::Node::checkReactionForce; the node: 2 has not constraints on DOF: 4 and, however, it has a reaction with value: 114.361 on this degree of freedom, it seems that the solution method and/or tolerances are not well suited to the problem. (tol= 19.2473

Does it ring any bells?

**Comment by lcpt** [comment]
Hi.

The prestressing steel material is not linear, so you need to use a nonlinear solver to reach equilibrium.

Regards.
Luis.

**Comment by anaiortega** [comment]
Yeah, Newton-Raphson converges. The error is anyway 2%, I suppose it's acceptable.
Thank you

**Comment by lcpt** [comment]
If you want to get an smaller error, you can reduce the tolerance.
