### ISSUE TITLE
Bash script to install on linux

### ISSUE THREAD

**Issue by shahram10715** [xcfem/xc#59]
Is there any possibility to write a bash script to execute the commands:

https://github.com/xcfem/xc/blob/master/install/install.linux.md

and install xc on Ubuntu?

**Comment by lcpt** [comment]
Hi.

Yes, there is already a script written by @berndhahnebach that installs xc on Ubuntu. Take a look [here](https://github.com/xcfem/xc/blob/master/install/install.scipts.linux.md).

**Comment by berndhahnebach** [comment]
@shahram10715 

would be cool if you could give some feedback if the scripts worked for you!

cheers bernd

**Comment by shahram10715** [comment]
dear Mr. @berndhahnebach 
First of all sorry for my late response, I tried the script and I encountered the following error

    mayavi-4.6.2.tar.bz2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    File "<string>", line 1, in <module>
    ImportError: No module named setuptools```

then I tried manually the following command:

    sudo apt install mayavi2

again I had trouble installing mayavi, and it was due to vtk libraries, so first I installed:

    sudo apt install vtk7

after these steps everything was working properly until run_verif.sh.
I realized that tkinter was installed by means Anaconda and didn't recognized.
So again, I install python-tk and python3-tk manually.
the thing that I couldn't fix was an error in run_verif.sh for xc directory. 
Here id the error:

    Verifiyng misc. utilities. 
    ERROR:root:rcond.py ERROR.```

I appreciate any information you can provide.

**Comment by berndhahnebach** [comment]
Which version of ubuntu do you use? Do you use original ubuntu?

**Comment by shahram10715** [comment]
I'm using the latest version of mint which is 19.1 on virtualbox.

**Comment by lcpt** [comment]
Hi.
This test (rcond.py) is on the directory xc/verif/tests/utility. Could you uncomment the line:
#print 'rcond= ', rcond
run the test and copy its output here?

**Comment by shahram10715** [comment]
here is the output of my verification, I can see two more errors in this file:

https://github.com/shahram10715/myPasteBeeens/blob/master/logFile01.txt

**Comment by lcpt** [comment]
Hi.

I see two errors: the first one in 'test_fiber_section_shear3d_02.py' I think is due to a numerical issue anyway the error reported is really small (0.00513). I'll take a look.

The second one is more mysterious. For some reason your Lapack implementation seems to return a different value for the condition number. I've added another test using Numpy to test again that the result are correct (see the new version of rcond.py in the repository).

**Comment by shahram10715** [comment]
Its fixed, thank you so much. and here is my log file:
https://github.com/shahram10715/myPasteBeeens/blob/master/logFile02.txt
what should I do now? should I execute the following command:

    sudo sh local_install.sh

or I should go through the whole process again?

**Comment by shahram10715** [comment]
There is still an error in line 512:
https://github.com/shahram10715/myPasteBeeens/blob/master/logFile02.txt

**Comment by shahram10715** [comment]
again the same problem with the following output:
https://github.com/shahram10715/myPasteBeeens/blob/master/logFile02.txt

**Comment by lcpt** [comment]
Yeah, the only difference is that, now, we know there is a problem with the calling to the LAPACK dlange function: 

https://github.com/xcfem/xc/blob/d8150601807370808a3b9c9251be8d3b7c46c155/src/utility/matrix/Matrix.cpp#L1764

Maybe "linux mint" uses a different version of LAPACK libraries. I have not the time to deal whit this right now but I'll take a look soon. Nevertheless, this is not a critical error. The program can be used normally despite this problem.
