### ISSUE TITLE
Error installing on Ubuntu 20.04

### ISSUE THREAD

**Issue by ebrahimraeyat** [xcfem/xc#68]
Hi @lcpt. I wanted to install XC on my Ubuntu 20 system. For installing dependency it seems there is no libgmsh3 package:

`E: Unable to locate package libgmsh3`

then I ran: 

`cmake ../xc_utils/src`

but it gives me this error:

-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
CMake Warning (dev) at /usr/share/cmake-3.16/Modules/FindOpenGL.cmake:275 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  /home/ebi/xc/build_xc/xc_utils/CMake/find_packages.cmake:3 (find_package)
  CMakeLists.txt:37 (INCLUDE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- The imported target "vtkParseOGLExt" references the file
   "/usr/bin/vtkParseOGLExt-7.1"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-7.1/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtkRenderingPythonTkWidgets" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkRenderingPythonTkWidgets.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-7.1/VTKTargets.cmake"
but not all the files it references.

-- The imported target "vtk" references the file
   "/usr/bin/vtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-7.1/VTKTargets.cmake"
but not all the files it references.

-- The imported target "pvtk" references the file
   "/usr/bin/pvtk"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/cmake/vtk-7.1/VTKTargets.cmake"
but not all the files it references.

-- Some or all of the gtk libraries were not found. (missing: GTK2_GTK_LIBRARY GTK2_GTK_INCLUDE_DIR GTK2_GDK_INCLUDE_DIR GTK2_GDKCONFIG_INCLUDE_DIR GTK2_GDK_LIBRARY) 
CMake Error at /home/ebi/xc/build_xc/xc_utils/CMake/find_packages.cmake:7 (find_package):
  By not providing "FindCGAL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "CGAL", but
  CMake did not find one.

  Could not find a package configuration file provided by "CGAL" with any of
  the following names:

    CGALConfig.cmake
    cgal-config.cmake

  Add the installation prefix of "CGAL" to CMAKE_PREFIX_PATH or set
  "CGAL_DIR" to a directory containing one of the above files.  If "CGAL"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:37 (INCLUDE)

-- Configuring incomplete, errors occurred!
See also "/home/ebi/xc/build_xc/build-xc_utils/CMakeFiles/CMakeOutput.log".
ebi@kubuntu20-Lenovo-Z51-70:~/xc/build_xc/build-xc_utils$

I used this help for installation:

`https://github.com/xcfem/xc/blob/master/install/install.scripts.linux.md#ubuntu-focal-fossa-ubuntu-20`

Thanks alot.

_Originally posted by @ebrahimraeyat in https://github.com/xcfem/xc/discussions/67_

**Comment by lcpt** [comment]
Hi @ebrahimraeyat 

There was an error in a package name here: 
https://github.com/xcfem/xc/blob/5dcb28d6ef0acf863de5244a4135c7f92915431a/install/packages_install_ubuntu_focal_fossa.sh#L39

I've fixed it. Could you download [packages_install_ubuntu_focal_fossa.sh](https://raw.githubusercontent.com/xcfem/xc/5dcb28d6ef0acf863de5244a4135c7f92915431a/install/packages_install_ubuntu_focal_fossa.sh) again and give it a try?

Thanks.

**Comment by ebrahimraeyat** [comment]
Thanks, it corrected this error and compile xc_utils complete. the test passes.
but for compiling XC, in 95% it gives me this error:
```
[ 95%] Building CXX object CMakeFiles/XcBib.dir/preprocessor/multi_block_topology/entities/3d/UniformGrid.cc.o
make[2]: *** [CMakeFiles/XcBib.dir/build.make:15897: CMakeFiles/XcBib.dir/preprocessor/multi_block_topology/entities/2d/PolygonalFace.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/ebi/xc/build_xc/xc/src/preprocessor/multi_block_topology/entities/3d/Block.cc: In member function ‘void XC::Block::create_nodes()’:
/home/ebi/xc/build_xc/xc/src/preprocessor/multi_block_topology/entities/3d/Block.cc:449:19: warning: unused variable ‘top’ [-Wunused-variable]
  449 |         BodyFace &top= sups[5];
      |                   ^~~
/home/ebi/xc/build_xc/xc/src/preprocessor/multi_block_topology/entities/3d/Block.cc:450:19: warning: unused variable ‘leftFace’ [-Wunused-variable]
  450 |         BodyFace &leftFace= sups[1];
      |                   ^~~~~~~~
/home/ebi/xc/build_xc/xc/src/preprocessor/multi_block_topology/entities/3d/Block.cc:451:19: warning: unused variable ‘rightFace’ [-Wunused-variable]
  451 |         BodyFace &rightFace= sups[3];
      |                   ^~~~~~~~~
/home/ebi/xc/build_xc/xc/src/preprocessor/multi_block_topology/entities/3d/Block.cc:452:19: warning: unused variable ‘frontFace’ [-Wunused-variable]
  452 |         BodyFace &frontFace= sups[2];
      |                   ^~~~~~~~~
/home/ebi/xc/build_xc/xc/src/preprocessor/multi_block_topology/entities/3d/Block.cc:453:19: warning: unused variable ‘backFace’ [-Wunused-variable]
  453 |         BodyFace &backFace= sups[4];
      |                   ^~~~~~~~
/home/ebi/xc/build_xc/xc/src/preprocessor/multi_block_topology/entities/3d/Block.cc:477:21: warning: unused variable ‘n3’ [-Wunused-variable]
  477 |         const Node *n3= ttzNodes(1,n_rows,n_cols);
      |                     ^~
/home/ebi/xc/build_xc/xc/src/preprocessor/multi_block_topology/entities/3d/Block.cc:479:21: warning: unused variable ‘n5’ [-Wunused-variable]
  479 |         const Node *n5= ttzNodes(n_layers,1,1);
      |                     ^~
/home/ebi/xc/build_xc/xc/src/preprocessor/multi_block_topology/entities/3d/Block.cc:480:21: warning: unused variable ‘n6’ [-Wunused-variable]
  480 |         const Node *n6= ttzNodes(n_layers,n_rows,1);
      |                     ^~
/home/ebi/xc/build_xc/xc/src/preprocessor/multi_block_topology/entities/3d/Block.cc:481:21: warning: unused variable ‘n7’ [-Wunused-variable]
  481 |         const Node *n7= ttzNodes(n_layers,n_rows,n_cols);
      |                     ^~
/home/ebi/xc/build_xc/xc/src/preprocessor/multi_block_topology/entities/3d/Block.cc:482:21: warning: unused variable ‘n8’ [-Wunused-variable]
  482 |         const Node *n8= ttzNodes(n_layers,1,n_cols);
      |                     ^~
make[1]: *** [CMakeFiles/Makefile2:107: CMakeFiles/XcBib.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by ebrahimraeyat** [comment]
Continuing of above error:
```
[sudo] password for ebi: 
[  0%] Building CXX object CMakeFiles/XcBib.dir/preprocessor/multi_block_topology/entities/2d/PolygonalFace.cc.o
/home/ebi/xc/build_xc/xc/src/preprocessor/multi_block_topology/entities/2d/PolygonalFace.cc: In member function ‘int XC::PolygonalFace::create_elements_from_gmsh(const std::map<int, const XC::Node*>&)’:
/home/ebi/xc/build_xc/xc/src/preprocessor/multi_block_topology/entities/2d/PolygonalFace.cc:620:129: error: too many arguments to function ‘void gmsh::model::mesh::getElementProperties(int, std::string&, int&, int&, int&, std::vector<double>&)’
  620 |      gmsh::model::mesh::getElementProperties(elementTypes[i], elementName, dim, order, numNodes, localNodeCoord, numPrimaryNodes);
      |                                                                                                                                 ^
In file included from /home/ebi/xc/build_xc/xc/src/preprocessor/multi_block_topology/entities/2d/PolygonalFace.cc:39:
/usr/include/gmsh.h:557:21: note: declared here
  557 |       GMSH_API void getElementProperties(const int elementType,
      |                     ^~~~~~~~~~~~~~~~~~~~
/home/ebi/xc/build_xc/xc/src/preprocessor/multi_block_topology/entities/2d/PolygonalFace.cc: In member function ‘void XC::PolygonalFace::gen_mesh_gmsh(XC::meshing_dir)’:
/home/ebi/xc/build_xc/xc/src/preprocessor/multi_block_topology/entities/2d/PolygonalFace.cc:700:15: warning: unused variable ‘numElements’ [-Wunused-variable]
  700 |     const int numElements= create_elements_from_gmsh(mapNodes);
      |               ^~~~~~~~~~~
make[2]: *** [CMakeFiles/XcBib.dir/build.make:15897: CMakeFiles/XcBib.dir/preprocessor/multi_block_topology/entities/2d/PolygonalFace.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:107: CMakeFiles/XcBib.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
path to libs: /usr/local/lib/python3.8/dist-packages
running install
running build
running build_py
running install_lib
running install_data
error: can't copy 'extensions/xc.so': doesn't exist or not a regular file
Updating installed files history.
cat: installed_files.txt: No such file or directory
rm: cannot remove 'installed_files.txt': No such file or directory

 Misc. tests. 
test  test_evalPy.py : ok.
test  test_execPy.py : ok.
test  testStairCaseFunction.py : ok.
test  test_linear_interpolation.py : ok.
 Soil mechanics. 
test  test_mononobe_okabe.py : ok.
.
.
.
12.783867642 seconds
76 tests
.16820878476315789473 seconds/test

 Actions tests. 
test  test_snowSIA.py : ok.
test  test_windSIA.py : ok.
Traceback (most recent call last):
  File "tests/actions/test_wind_cylindr_01.py", line 9, in <module>
    from actions.wind import base_wind as bw
  File "/usr/local/lib/python3.8/dist-packages/actions/wind/base_wind.py", line 14, in <module>
    import xc
ModuleNotFoundError: No module named 'xc'
```
as you see, the test for xc_utils passes, but XC not compiled.

thanks.

**Comment by MaximilianFranz** [comment]
Hey everyone, 

just started putting together a Dockerfile based on Ubuntu 20.04 and stumbled across the same issue as @ebrahimraeyat: 

```bash
$ sudo python3 setup.py install
path to libs: /usr/lib/python3.8/dist-packages
running install
running build
running build_py
running install_lib
running install_data
error: can't copy 'extensions/xc.so': doesn't exist or not a regular file
```

I use `python3` directly, because in plain ubuntu doesn't have a `python` version install. In general, we should aim to use python within a conda environment or something, if that is a viable option, @lcpt ? 

I'll see if I find a solution for above problem and keep you posted! 

Thanks for the cool project, keep doing the good work!

**Comment by MaximilianFranz** [comment]
More specifially, `extensions/xc.so` in `python_modules` is a link: 
```bash
$ ls -ls extensions/
0 lrwxrwxrwx 1 root root 15 Dec 19 22:01 xc.so -> ../../lib/xc.so
```
but `lib` is empty..

**Comment by MaximilianFranz** [comment]
Seems like the error occurs in the build and hence the library file is not written, yet the script continues..

**Comment by lcpt** [comment]
> Continuing of above error:
> 
> ```
> [sudo] password for ebi: 
> [  0%] Building CXX object CMakeFiles/XcBib.dir/preprocessor/multi_block_topology/entities/2d/PolygonalFace.cc.o
> /home/ebi/xc/build_xc/xc/src/preprocessor/multi_block_topology/entities/2d/PolygonalFace.cc: In member function ‘int XC::PolygonalFace::create_elements_from_gmsh(const std::map<int, const XC::Node*>&)’:
> /home/ebi/xc/build_xc/xc/src/preprocessor/multi_block_topology/entities/2d/PolygonalFace.cc:620:129: error: too many arguments to function ‘void gmsh::model::mesh::getElementProperties(int, std::string&, int&, int&, int&, std::vector<double>&)’
>   620 |      gmsh::model::mesh::getElementProperties(elementTypes[i], elementName, dim, order, numNodes, localNodeCoord, numPrimaryNodes);
>       |                                                                                                                                 ^
> In file included from /home/ebi/xc/build_xc/xc/src/preprocessor/multi_block_topology/entities/2d/PolygonalFace.cc:39:
> /usr/include/gmsh.h:557:21: note: declared here
>   557 |       GMSH_API void getElementProperties(const int elementType,
>       |                     ^~~~~~~~~~~~~~~~~~~~
> /home/ebi/xc/build_xc/xc/src/preprocessor/multi_block_topology/entities/2d/PolygonalFace.cc: In member function ‘void XC::PolygonalFace::gen_mesh_gmsh(XC::meshing_dir)’:
> /home/ebi/xc/build_xc/xc/src/preprocessor/multi_block_topology/entities/2d/PolygonalFace.cc:700:15: warning: unused variable ‘numElements’ [-Wunused-variable]
>   700 |     const int numElements= create_elements_from_gmsh(mapNodes);
>       |               ^~~~~~~~~~~
> make[2]: *** [CMakeFiles/XcBib.dir/build.make:15897: CMakeFiles/XcBib.dir/preprocessor/multi_block_topology/entities/2d/PolygonalFace.cc.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:107: CMakeFiles/XcBib.dir/all] Error 2
> make: *** [Makefile:130: all] Error 2
> path to libs: /usr/local/lib/python3.8/dist-packages
> running install
> running build
> running build_py
> running install_lib
> running install_data
> error: can't copy 'extensions/xc.so': doesn't exist or not a regular file
> Updating installed files history.
> cat: installed_files.txt: No such file or directory
> rm: cannot remove 'installed_files.txt': No such file or directory
> 
>  Misc. tests. 
> test  test_evalPy.py : ok.
> test  test_execPy.py : ok.
> test  testStairCaseFunction.py : ok.
> test  test_linear_interpolation.py : ok.
>  Soil mechanics. 
> test  test_mononobe_okabe.py : ok.
> .
> .
> .
> 12.783867642 seconds
> 76 tests
> .16820878476315789473 seconds/test
> 
>  Actions tests. 
> test  test_snowSIA.py : ok.
> test  test_windSIA.py : ok.
> Traceback (most recent call last):
>   File "tests/actions/test_wind_cylindr_01.py", line 9, in <module>
>     from actions.wind import base_wind as bw
>   File "/usr/local/lib/python3.8/dist-packages/actions/wind/base_wind.py", line 14, in <module>
>     import xc
> ModuleNotFoundError: No module named 'xc'
> ```
> 
> as you see, the test for xc_utils passes, but XC not compiled.
> 
> thanks.

It's an error related to the version of the Gmsh API. I'm fixing it.

**Comment by lcpt** [comment]
> More specifially, `extensions/xc.so` in `python_modules` is a link:
> 
> ```shell
> $ ls -ls extensions/
> 0 lrwxrwxrwx 1 root root 15 Dec 19 22:01 xc.so -> ../../lib/xc.so
> ```
> 
> but `lib` is empty..
> 
> Also, I found that running `make -j 2` in `xc-build` leads to an error, which seems to be skipped in the install script somehow:
> 
> ```
> root@e9e08f326e4a:/modugen/build_xc/build-xc# make
> Scanning dependencies of target XcBib
> [  0%] Building CXX object CMakeFiles/XcBib.dir/preprocessor/multi_block_topology/entities/2d/PolygonalFace.cc.o
> /modugen/build_xc/xc/src/preprocessor/multi_block_topology/entities/2d/PolygonalFace.cc: In member function 'int XC::PolygonalFace::create_elements_from_gmsh(const std::map<int, const XC::Node*>&)':
> /modugen/build_xc/xc/src/preprocessor/multi_block_topology/entities/2d/PolygonalFace.cc:620:129: error: too many arguments to function 'void gmsh::model::mesh::getElementProperties(int, std::string&, int&, int&, int&, std::vector<double>&)'
>   620 |      gmsh::model::mesh::getElementProperties(elementTypes[i], elementName, dim, order, numNodes, localNodeCoord, numPrimaryNodes);
>       |                                                                                                                                 ^
> In file included from /modugen/build_xc/xc/src/preprocessor/multi_block_topology/entities/2d/PolygonalFace.cc:39:
> /usr/include/gmsh.h:557:21: note: declared here
>   557 |       GMSH_API void getElementProperties(const int elementType,
>       |                     ^~~~~~~~~~~~~~~~~~~~
> /modugen/build_xc/xc/src/preprocessor/multi_block_topology/entities/2d/PolygonalFace.cc: In member function 'void XC::PolygonalFace::gen_mesh_gmsh(XC::meshing_dir)':
> /modugen/build_xc/xc/src/preprocessor/multi_block_topology/entities/2d/PolygonalFace.cc:700:15: warning: unused variable 'numElements' [-Wunused-variable]
>   700 |     const int numElements= create_elements_from_gmsh(mapNodes);
>       |               ^~~~~~~~~~~
> make[2]: *** [CMakeFiles/XcBib.dir/build.make:15897: CMakeFiles/XcBib.dir/preprocessor/multi_block_topology/entities/2d/PolygonalFace.cc.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:107: CMakeFiles/XcBib.dir/all] Error 2
> make: *** [Makefile:130: all] Error 2
> root@e9e08f326e4a:/modugen/build_xc/build-xc# make -j 2
> [  0%] Building CXX object CMakeFiles/XcBib.dir/preprocessor/multi_block_topology/entities/2d/PolygonalFace.cc.o
> [  0%] Building CXX object CMakeFiles/XcBib.dir/preprocessor/multi_block_topology/entities/3d/Body.cc.o
> /modugen/build_xc/xc/src/preprocessor/multi_block_topology/entities/2d/PolygonalFace.cc: In member function 'int XC::PolygonalFace::create_elements_from_gmsh(const std::map<int, const XC::Node*>&)':
> /modugen/build_xc/xc/src/preprocessor/multi_block_topology/entities/2d/PolygonalFace.cc:620:129: error: too many arguments to function 'void gmsh::model::mesh::getElementProperties(int, std::string&, int&, int&, int&, std::vector<double>&)'
>   620 |      gmsh::model::mesh::getElementProperties(elementTypes[i], elementName, dim, order, numNodes, localNodeCoord, numPrimaryNodes);
>       |                                                                                                                                 ^
> In file included from /modugen/build_xc/xc/src/preprocessor/multi_block_topology/entities/2d/PolygonalFace.cc:39:
> /usr/include/gmsh.h:557:21: note: declared here
>   557 |       GMSH_API void getElementProperties(const int elementType,
>       |                     ^~~~~~~~~~~~~~~~~~~~
> /modugen/build_xc/xc/src/preprocessor/multi_block_topology/entities/2d/PolygonalFace.cc: In member function 'void XC::PolygonalFace::gen_mesh_gmsh(XC::meshing_dir)':
> /modugen/build_xc/xc/src/preprocessor/multi_block_topology/entities/2d/PolygonalFace.cc:700:15: warning: unused variable 'numElements' [-Wunused-variable]
>   700 |     const int numElements= create_elements_from_gmsh(mapNodes);
>       |               ^~~~~~~~~~~
> make[2]: *** [CMakeFiles/XcBib.dir/build.make:15897: CMakeFiles/XcBib.dir/preprocessor/multi_block_topology/entities/2d/PolygonalFace.cc.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[1]: *** [CMakeFiles/Makefile2:107: CMakeFiles/XcBib.dir/all] Error 2
> make: *** [Makefile:130: all] Error 2
> ```
Hi.

It's the same error (different Gmsh API versions). Working on it.

**Comment by MaximilianFranz** [comment]
Jep it is. Thanks! :)

**Comment by MaximilianFranz** [comment]
> It's the same error (different Gmsh API versions). Working on it.

Which version should it be? Can we solve it by just pinning the version in the dependencies?

**Comment by lcpt** [comment]
Hi again.

I think it's solved. Now it works with Gmsh 4.4 (the version that comes with Ubuntu 20.04) and 4.7 (the version I installed in Ubuntu 18.04 some months ago).

I've fixed some other minor caveats, so you'll need to download [packages_install_ubuntu_focal_fossa.sh](https://raw.githubusercontent.com/xcfem/xc/5dcb28d6ef0acf863de5244a4135c7f92915431a/install/packages_install_ubuntu_focal_fossa.sh) and run it again. You will also need to pull both repositories: xc_utils and xc and repeat the compiling/installing process (this time it will be faster; only a small part of the c++ code of the xc repository has been modified). 

If you found any further problems, please let me know.

**Comment by lcpt** [comment]
I'll close this. We can always reopen if needed.

**Comment by MaximilianFranz** [comment]
Jep, I am running the build right now. I'll let you now if any new errors arise.

**Comment by MaximilianFranz** [comment]
Works like a charm! Thank's alot for the fast reply!

**Comment by lcpt** [comment]
My pleasure!

**Comment by ebrahimraeyat** [comment]
Fixed, thanks a lot. Only problem with two tests:
1- for pyexcel library, it seems it is not in installation dependencies:
```
import pyexcel as pe
ModuleNotFoundError: No module named 'pyexcel'
```
2- it seems it is warning:
```
 Verifiying routines for rough calculations,... 
test  test_punzo01.py : ok.
...
test  test_base_plate_design.py : ok.
**convert-im6.q16: attempt to perform an operation not allowed by the security policy `EPS' @ error/constitute.c/IsCoderAuthorized/408.**
test  retaining_wall_test_01.py : ok.
 Verifiying routines for post processing.
```
Thank you so much.

**Comment by lcpt** [comment]
Hi @ebrahimraeyat.

About the pyexcel problem, yesterday I added the following lines:
```
sudo -H pip3 install pyexcel
sudo -H pip3 install pyexcel-ods
```
To the `packages_install_ubuntu_focal_fossa.sh` script, so normally the problem is addressed now.

The second problem occurs when using ImageMagick `convert` command with postscript or PDF files.  Some time ago PDF was disabled due to its inherent insecurity. You can remove this policy if you want (I did, but I don't remember how). Anyway I will make the conversion to postscript optional to avoid this error.

**Comment by ebrahimraeyat** [comment]
Thank you so much.

**Comment by lcpt** [comment]
I've made creation of postscript files optional. Could you run `retaining_wall_test_01.py` again to see if it works?

**Comment by ebrahimraeyat** [comment]
```ebi@kubuntu20-Lenovo-Z51-70:~/xc/build_xc/xc/verif$ python tests/rough_calculations/retaining_wall_test_01.py
convert-im6.q16: attempt to perform an operation not allowed by the security policy `EPS' @ error/constitute.c/IsCoderAuthorized/408.
test  retaining_wall_test_01.py : ok.
ebi@kubuntu20-Lenovo-Z51-70:~/xc/build_xc/xc/verif$ 
```

thanks a lot.

**Comment by lcpt** [comment]
So the error persists...

Have you reinstalled the updated python modules?
```
cd xc/python_modules
sh local_install.sh
```

**Comment by ebrahimraeyat** [comment]
> So the error persists...
> 
> Have you reinstalled the updated python modules?
> 
> ```
> cd xc/python_modules
> sh local_install.sh
> ```

oh, No, I did it and error fixed, thanks.

```
ebi@kubuntu20-Lenovo-Z51-70:~/xc/build_xc/xc/verif$ python tests/rough_calculations/retaining_wall_test_01.py
test  retaining_wall_test_01.py : ok.
ebi@kubuntu20-Lenovo-Z51-70:~/xc/build_xc/xc/verif$ 
```

**Comment by lcpt** [comment]
Perfect. Thanks to you.

**Comment by Josileissu** [comment]
Well, now its me with an error.

```
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (rank-1 and scalar)
make[2]: *** [CMakeFiles/xc_basic_utils.dir/build.make:1018: CMakeFiles/xc_basic_utils.dir/umfpack/umd2f0.f.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:218: CMakeFiles/xc_basic_utils.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```
What i do for now.
1) Install Ubuntu 21.04;
2) Run the script;
3) Mkdir build_xc;
4) clone xc_utils and xc at ~/build_xc$
5) mkdir build-xc_utils, cmake src, make -j 12 (for testing) and here i get this two errors.

How can i undo these final step? To cmake and make again? or i cant?
