### ISSUE TITLE
Two method with same names in AISC Member class

### ISSUE THREAD

**Issue by ebrahimraeyat** [xcfem/xc#85]
It seems two method with the same name in line 142 and 149:

https://github.com/xcfem/xc/blob/5b6d13d06325450efe0159cbcb520273bb353891/python_modules/materials/astm_aisc/AISC_limit_state_checking.py#L142

https://github.com/xcfem/xc/blob/5b6d13d06325450efe0159cbcb520273bb353891/python_modules/materials/astm_aisc/AISC_limit_state_checking.py#L149

**Comment by lcpt** [comment]
Hi, @ebrahimraeyat. Thanks!

You're right, the first method has the wrong name (it returns the flexural strength reduction factor). I've not detected any calls to this method anywhere so, probably, the problem ends here.
