### ISSUE TITLE
When i try to clone this directory an error is caused - aisc_shapes_database...

### ISSUE THREAD

**Issue by Josileissu** [xcfem/xc#94]
**Describe the bug**
I'm a windows user (for now) and i want to know more about XC engineering and improve after understand the codes... But, im getting an error when i try to clone this repository.
![image](https://user-images.githubusercontent.com/53374605/116821534-a346ed80-ab50-11eb-897b-e9f8a900d6f1.png)

I already just download with zip project and extract, but shows a lot of warnings.

**Comment by ebrahimraeyat** [comment]
Hello @Josileissu. XC only runs on Linux, although this error it is not related to OS.

**Comment by Josileissu** [comment]
Oh, i got it.
So, if i started to use xc with windows o.s. maybe any functionality from the software, like opensees, cgal, vtk, may not work correct? or others librarys may not run properly?

I know the python is multiplataform, so if i study the codes i can apply in the windows, but i will have troubles with these other programs?

**Comment by ebrahimraeyat** [comment]
You can't use xc on Windows, because it can't be compiled on Windows. Of course, you can study the source code, but if you want to test and work on xc, you must use Linux OS.

**Comment by lcpt** [comment]
Hi @Josileissu 

You can install Ubuntu on Windows 10 (take a look [here](https://ubuntu.com/tutorials/ubuntu-on-windows#1-overview) and [here](https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6?activetab=pivot:overviewtab)).

You'll need an [XWindow](https://en.wikipedia.org/wiki/X_Window_System) server for Windows 10 (apparently Microsoft has plans to integrate an XWindow server inside Windows, but I think there is nothing usable yet). Anyway, you can use [Xming]( http://www.straightrunning.com/XmingNotes/) which works just fine.

That way, you can use XC and many useful Linux programs in your Windows machine. The only problem is that you'll get a lower performance (we can compare test results if you are interested).

**Comment by ebrahimraeyat** [comment]
Hi @lcpt. I didn't know that it is usable in windows. You mean, you are using XC on Windows with above way? I will try that. Thanks.

**Comment by lcpt** [comment]
No, I almost always use an Ubuntu or Debian computer, but, for example @AlexandreMagnolc has installed XC using the [Windows subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10).

**Comment by lcpt** [comment]
Hi @Josileissu.  If you need any assistance, please let me know.

**Comment by Josileissu** [comment]
Wow, @lcpt. Thanks for reply and assistance.

Well, i will create a dual boot on my computer for correctly use and study xc. I wanna extended the open source software for brazilian codes before understand the program.

For now, i'm happy with your attention.

Thx.

**Comment by lcpt** [comment]
OK, so I'll close this issue.

Cheers.
