### ISSUE TITLE
undefined symbol error in importing xc

### ISSUE THREAD

**Issue by ebrahimraeyat** [xcfem/xc#99]
Hi @lcpt. finally I compiled xc on my ubuntu 20.04 in my wsl in windows 10. but one error:

```
ebrahim@DESKTOP-GT2QLMA:~/xc$ python
Python 3.8.10 (default, Sep 28 2021, 16:10:42)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import xc_base
>>> import geom
>>> import xc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/ebrahim/xc/build_xc/xc/lib/libXcBib.so: undefined symbol: _ZN4gmsh5model3geo12addCurveLoopERKSt6vectorIiSaIiEEib
>>>
```

Thanks

**Comment by ebrahimraeyat** [comment]
finally I installed it successfully, but some test gives me this error:

```
(test_uls_checking_aisc_05.py:15708): Gdk-CRITICAL **: 08:11:24.670: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
test test_uls_checking_aisc_05.py: ok.
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
```

and also when I want to run my [previous model](https://github.com/ebrahimraeyat/xc_soleh), it gives the segmentation fault error, I think it is related to graphic show. I installed xming, but it is not corrected.

**Comment by lcpt** [comment]
So now it's running. Good news.
I think it's better to close this issue, and open a new issue for each new problem. This way, they can serve as a reference for other users with similar problems.
